builder:
  build: .
  volumes:
    - .:/src

server:
  image: nginx
  volumes:
    - ./app/public:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - /etc/letsencrypt:/etc/letsencrypt/
  ports:
    - "80:80"
    - "443:443"

letsencrypt:
  image: quay.io/letsencrypt/letsencrypt:latest
  command: certonly --renew-by-default --domains="te.chie.la"
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
