version: '2'
services:

  builder:
    build:
        context: .
        dockerfile: Dockerfile.build
    volumes:
      - .:/src

  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
